    [[redirects]]
    from = "/*"
    to = "/"
    status = 200 


  [build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/uploads/*"
  to = "/.netlify/functions/uploads/:splat"
  status = 200