[[redirects]]
  from = "/product-images/*"
  to = "/.netlify/functions/get-image?key=:splat"
  status = 200
  force = true

# For direct blob access (if needed)
[[redirects]]
  from = "/blobs/*"
  to = "/.netlify/blobs/:splat"
  status = 200
  force = true

# Image transformations
[[redirects]]
  from = "/_image"
  to = "/.netlify/image"
  status = 200
  force = true

[[headers]]
  for = "/product-images/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000, immutable"