import OPPOA57 from "assets/oppo/OPPOA57.jpg";
import OPPOA17K from "assets/oppo/OPPOA17K.jpg";
import OPPOA77 from "assets/oppo/OPPOA77.jpg";
import OPPOK12X from "assets/oppo/OPPOK12X.jpg";
import OPPORENO12PRO from "assets/oppo/OPPORENO12PRO.jpg";
import OPPORENO12 from "assets/oppo/OPPORENO12.jpg";
import OPPOF27PROPLUS from "assets/oppo/OPPOF27PROPLUS.jpg";
import OPPOF27 from "assets/oppo/OPPOF27.jpg";
import OPPOA3PRO from "assets/oppo/OPPOA3PRO.jpg";
import OPPOA3X from "assets/oppo/OPPOA3X.jpg";

export const OPPOPHONES = [
  {
    name: "OPPO A57 4/64 ",
    image: OPPOA57,
    salesPrice: 10999,
    mrp: 16990,
    specification: {},
  },

  {
    name: "OPPO A17K 3/64 ",
    image: OPPOA17K,
    salesPrice: 8499,
    mrp: 12999,
    specification: {},
  },

  {
    name: "OPPO A77 4/128 ",
    image: OPPOA77,
    salesPrice: 15999,
    mrp: 19999,
    specification: {},
  },

  {
    name: "OPPO K12X 8/256 ",
    image: OPPOK12X,
    salesPrice: 16000,
    mrp: 18999,
    specification: {
      "In The Box ":
        " Handset, Charger, USB Data Cable, Sim Ejector Tool, Quick Guide, Protective Case",
      "Model Number ": " CPH2667",
      "Model Name ": " K12x 5G",
      "Color ": " Midnight Violet",
      "Browse Type ": " Smartphones",
      "SIM Type ": " Dual Sim",
      "Hybrid Sim Slot ": " Yes",
      "Touchscreen ": " Yes",
      "OTG Compatible ": " Yes",
      "Quick Charging ": " Yes",
      "Additional Content ": " with 45W SUPERVOOC Charger In-The-Box",
      "Display Size ": " 16.94 cm (6.67 inch)",
      "Resolution ": " 1604 x 720 Pixels",
      "Resolution Type ": " HD",
      "GPU ": " G57 MC2",
      "Display Type ": " LCD",
      "Operating System ": " Android 14",
      "Processor Brand ": " Mediatek",
      "Processor Type ": " Dimensity 6300",
      "Processor Core ": " Octa Core",
      "Primary Clock Speed ": " 2.4 GHz",
      "Secondary Clock Speed ": " 2 GHz",
      "Internal Storage ": " 256 GB",
      "RAM ": " 8 GB",
      "Expandable Storage ": " 1 TB",
      "Supported Memory Card Type ": " MicroSD",
      "Memory Card Slot Type ": " Hybrid Slot",
      "Primary Camera Available ": " Yes",
      "Primary Camera ": " 32MP + 2MP",
      "Primary Camera Features ":
        " Dual Camera Setup: 32MP Ultra Clear Main Camera (GC32E2 Sensor, f/1.8 Aperture, 1/3.1 inch Sensor Size, 0.7um Pixel Size, 27mm Focal Length, 5P Lens, Supporting Aoto Focus + 2MP Portrait Camera (GC02M1B Sensor, f/2.4 Aperture, 1/5 inch Sensor Size, 1.75um Pixel Size, 22mm Focal Length, 3P Lens",
      "Secondary Camera Available ": " Yes",
      "Secondary Camera ": " 8MP Front Camera",
      "Secondary Camera Features ":
        " Front Camera: 8MP Camera (GC08A8-WA1XA Sensor, f/2.05 Aperture, 1/4 inch Sensor Size, 1.12um Pixel Size, 25mm Focal Length, 4P Lens",
      "Flash ": " Cosmic Flashlight",
      "Full HD Recording ": " Yes",
      "Video Recording ": " Yes",
      "Dual Camera Lens ": " Primary Camera",
      "Video Call Support ": " Yes",
      "Network Type ": " 5G, 4G, 3G, 2G",
      "Supported Networks ": " 5G, 4G LTE, WCDMA, GSM",
      "Internet Connectivity ": " 5G. 4G, WiFi",
      "3G ": " Yes",
      "Micro USB Port ": " Yes",
      "Wi-Fi ": " Yes",
      "Wi-Fi Hotspot ": " Yes",
      "NFC ": " Yes",
      "USB Connectivity ": " Yes",
      "GPS Support ": " Yes",
      "Smartphone ": " Yes",
      "SIM Size ": " Nano Sim",
      "SMS ": " Yes",
      "Graphics PPI ": " 264 PPI",
      "Battery Capacity ": " 5100 mAh",
      "Depth ": " 7.68 mm",
      "Weight ": " 186 g",
      "Domestic Warranty ": " 1 Year",
    },
  },

  {
    name: "OPPO K12X 6/128 ",
    image: OPPOK12X,
    salesPrice: 13000,
    mrp: 16999,
    specification: {
      "In The Box ":
        " Handset, Charger, USB Data Cable, Sim Ejector Tool, Quick Guide, Protective Case",
      "Model Number ": " CPH2667",
      "Model Name ": " K12x 5G",
      "Color ": " Midnight Violet",
      "Browse Type ": " Smartphones",
      "SIM Type ": " Dual Sim",
      "Hybrid Sim Slot ": " Yes",
      "Touchscreen ": " Yes",
      "OTG Compatible ": " Yes",
      "Quick Charging ": " Yes",
      "Additional Content ": " with 45W SUPERVOOC Charger In-The-Box",
      "Display Size ": " 16.94 cm (6.67 inch)",
      "Resolution ": " 1604 x 720 Pixels",
      "Resolution Type ": " HD",
      "GPU ": " G57 MC2",
      "Display Type ": " LCD",
      "Operating System ": " Android 14",
      "Processor Brand ": " Mediatek",
      "Processor Type ": " Dimensity 6300",
      "Processor Core ": " Octa Core",
      "Primary Clock Speed ": " 2.4 GHz",
      "Secondary Clock Speed ": " 2 GHz",
      "Internal Storage ": " 128 GB",
      "RAM ": " 6 GB",
      "Expandable Storage ": " 1 TB",
      "Supported Memory Card Type ": " MicroSD",
      "Memory Card Slot Type ": " Hybrid Slot",
      "Primary Camera Available ": " Yes",
      "Primary Camera ": " 32MP + 2MP",
      "Primary Camera Features ":
        " Dual Camera Setup: 32MP Ultra Clear Main Camera (GC32E2 Sensor, f/1.8 Aperture, 1/3.1 inch Sensor Size, 0.7um Pixel Size, 27mm Focal Length, 5P Lens, Supporting Aoto Focus + 2MP Portrait Camera (GC02M1B Sensor, f/2.4 Aperture, 1/5 inch Sensor Size, 1.75um Pixel Size, 22mm Focal Length, 3P Lens",
      "Secondary Camera Available ": " Yes",
      "Secondary Camera ": " 8MP Front Camera",
      "Secondary Camera Features ":
        " Front Camera: 8MP Camera (GC08A8-WA1XA Sensor, f/2.05 Aperture, 1/4 inch Sensor Size, 1.12um Pixel Size, 25mm Focal Length, 4P Lens",
      "Flash ": " Cosmic Flashlight",
      "Full HD Recording ": " Yes",
      "Video Recording ": " Yes",
      "Dual Camera Lens ": " Primary Camera",
      "Video Call Support ": " Yes",
      "Network Type ": " 5G, 4G, 3G, 2G",
      "Supported Networks ": " 5G, 4G LTE, WCDMA, GSM",
      "Internet Connectivity ": " 5G. 4G, WiFi",
      "3G ": " Yes",
      "Micro USB Port ": " Yes",
      "Wi-Fi ": " Yes",
      "Wi-Fi Hotspot ": " Yes",
      "NFC ": " Yes",
      "USB Connectivity ": " Yes",
      "GPS Support ": " Yes",
      "Smartphone ": " Yes",
      "SIM Size ": " Nano Sim",
      "SMS ": " Yes",
      "Graphics PPI ": " 264 PPI",
      "Battery Capacity ": " 5100 mAh",
      "Depth ": " 7.68 mm",
      "Weight ": " 186 g",
      "Domestic Warranty ": " 1 Year",
    },
  },

  {
    name: "OPPO RENO12 PRO 12/256 ",
    image: OPPORENO12PRO,
    salesPrice: 36999,
    mrp: 53999,
    specification: {
      "Sim Type ": " Dual SIM",
      "Hybrid Sim ": " Yes",
      "Memory Card Slot ": " Hybrid Slot",
      "Display Size ": " 17.02 cm (6.7 inch)",
      "Display Type ": " Flexible AMOLED",
      "Resolution ": " 2412 x 1080 PIxels",
      "GPU ": " Arm Mali-G615",
      "Processor Type ": " MediaTek Dimensity 7300 Energy",
      "Speed & Core  ": " 2.5 GHz Octa-core",
      "O.S ": " Android v14",
      "Ram ": " 12 GB",
      "Rom ": " 256 GB",
      "Network ": " 5G, 4G, 3G, 2G",
      "Back Camera ": " 50MP + 8MP + 50MP",
      "Back Video ": " 4K@30fps,1080P",
      "Front Camera ": " 50 MP",
      "Battery ": " 5000mAh ",
      "Charger ": " 80W",
      "Weight  ": " 180g",
      "Sensor ":
        " Geomagnetic Sensor, In Display Proximity Sensor, In Display Optical Sensor, Acceleration Sensor, Gravity Sensor, Color Temperature Sensor, Gyroscope, Step Counting, Infrared Remote Contro",
    },
  },

  {
    name: "OPPO RENO12 8/256 ",
    image: OPPORENO12,
    salesPrice: 32999,
    mrp: 43999,
    specification: {
      "Sim Type ": " Dual SIM",
      "Hybrid Sim ": " Yes",
      "Memory Card Slot ": " Hybrid Slot",
      "Display Size ": " 17.02 cm (6.7 inch)",
      "Display Type ": " Flexible AMOLED",
      "Resolution ": " 1080x2412 px (FHD+)",
      "GPU ": " Mali-G615 MC2",
      "Processor Type ": " MediaTek Dimensity 7300 Energy",
      "Speed & Core  ": " 3.1 GHz Octa-core",
      "O.S ": " Android v14",
      "Ram ": " 8 GB",
      "Rom ": " 256 GB",
      "Network ": " 5G, 4G, 3G, 2G",
      "Back Camera ": " 50MP + 50MP + 8MP",
      "Back Video ": " 4K@30fps,1080P",
      "Front Camera ": " 50 MP",
      "Battery ": " 5000mAh ",
      "Charger ": " 80W",
      "Weight  ": " 177g",
      "Sensor ":
        " In-Display Fingerprint Sensor, Compass/ Magnetometer, Proximity sensor, Accelerometer, Ambient light sensor, Gyroscope",
    },
  },

  {
    name: "OPPO F27PRO+ 8/256 ",
    image: OPPOF27PROPLUS,
    salesPrice: 29999,
    mrp: 34999,
    specification: {
      "Sim Type ": " Dual SIM",
      "Hybrid Sim ": " No",
      "Memory Card Slot ": " Yes ",
      "Display Size ": " 17.02 cm (6.7 inch)",
      "Display Type ": " Full HD+ 3D Curved AMOLED",
      "Resolution ": " 2412 x 1080 Pixels",
      "GPU ": " ARM Mali-G68 MC4",
      "Processor Type ": " Dimensity 7050",
      "Speed & Core  ": " 2.6 GHz Octa-core ",
      "O.S ": " Android 14",
      "Ram ": " 8 GB",
      "Rom ": " 128 GB",
      "Network ": " 5G, 4G, 3G, 2G",
      "Back Camera ": " 64MP + 2MP ",
      "Back Video ": " 1080p@30fps",
      "Front Camera ": " 8 MP ",
      "Battery ": " 5000 mAh  ",
      "Charger ": " 33W ",
      "Weight  ": " 177 g",
      "Sensors ":
        " Fingerprint (under display, optical), accelerometer, gyro, proximity, compass",
    },
  },

  {
    name: "OPPO F27 8/256 ",
    image: OPPOF27,
    salesPrice: 24999,
    mrp: 28999,
    specification: {
      "Brand ": " Oppo",
      "Model ": " F27",
      "OS ": " Android 14",
      "RAM ": " 8 gb",
      "Batteries ": " 1 Lithium Ion batteries required. (included)",
      "Wireless communication technologies ": " Bluetooth, Cellular, Wi-Fi",
      "Connectivity technologies ": " Bluetooth, Wi-Fi, NFC",
      "GPS ": " GLONASS",
      "Special features ":
        " Fast Charging Support, Stereo Speakers, Dual SIM, Built-In GPS, Mobile Hotspot Capability",
      "Other display features ": " Wireless",
      "Device interface - primary ": " Touchscreen",
      "Resolution ": " 1080p",
      "Other camera features ": " Rear, Front",
      "Colour ": " Emerald Green",
      "Battery Power Rating ": " 5000",
      "Item Dimensions LxWxH ": " 16.3 x 7.6 x 0.8 Centimeters",
    },
  },

  {
    name: "OPPO A3 PRO 8/256 ",
    image: OPPOA3PRO,
    salesPrice: 19999,
    mrp: 22999,
    specification: {},
  },

  {
    name: "OPPO A3 PRO 8/128 ",
    image: OPPOA3PRO,
    salesPrice: 17999,
    mrp: 20999,
    specification: {},
  },

  {
    name: "OPPO A3X 4/128 ",
    image: OPPOA3X,
    salesPrice: 13499,
    mrp: 15999,
    specification: {
      "Sim Type ": " Dual Sim",
      "Hybrid Sim ": " Yes",
      "Memory Card Slot ": " Hybrid Slot ",
      "Display Size ": " 6.67 inches",
      "Display Type ": " HD+ LCD",
      "Resolution ": " 1604 x 720 Pixels",
      "GPU ": " ARM Mali G57 MC2",
      "Processor Type ": " Dimensity 6300",
      "Speed & Core  ": " 2.4 GHz Octa-core ",
      "O.S ": " Android 14",
      "Ram ": " 4 GB",
      "Rom ": " 128 GB",
      "Network ": " 5G,4G,3GB,2GB",
      "Back Camera ": " 8MP",
      "Back Video ": " 1080 @ 30 fps",
      "Front Camera ": " 5 MP",
      "Battery ": " 5100 mAh",
      "Charger ": " 45W",
      "Weight  ": " 187 g",
      "Sensors ":
        " Geomagnetic Sensor, Ambient Light Sensor, Proximity Sensor, Accelerometer, Gravity Sensor, Pedometer, Side Mounted Fingerprint Sensor.",
    },
  },
];
