import TECNOCAMON20ARTEDITION1 from "assets/tecno/TECNOCAMON20/TECNOCAMON20ARTEDITION/TECNOCAMON20ARTEDITION1.jpg";
import TECNOCAMON20ARTEDITION2 from "assets/tecno/TECNOCAMON20/TECNOCAMON20ARTEDITION/TECNOCAMON20ARTEDITION2.jpg";
import TECNOCAMON20ARTEDITION3 from "assets/tecno/TECNOCAMON20/TECNOCAMON20ARTEDITION/TECNOCAMON20ARTEDITION3.jpg";
import TECNOCAMON20ARTEDITION4 from "assets/tecno/TECNOCAMON20/TECNOCAMON20ARTEDITION/TECNOCAMON20ARTEDITION4.jpg";
import TECNOCAMON20ARTEDITION5 from "assets/tecno/TECNOCAMON20/TECNOCAMON20ARTEDITION/TECNOCAMON20ARTEDITION5.jpg";
import TECNOCAMON20SERENITYBLUE1 from "assets/tecno/TECNOCAMON20/TECNOCAMON20SERENITYBLUE/TECNOCAMON20SERENITYBLUE1.jpg";
import TECNOCAMON20SERENITYBLUE2 from "assets/tecno/TECNOCAMON20/TECNOCAMON20SERENITYBLUE/TECNOCAMON20SERENITYBLUE2.jpg";
import TECNOCAMON20SERENITYBLUE3 from "assets/tecno/TECNOCAMON20/TECNOCAMON20SERENITYBLUE/TECNOCAMON20SERENITYBLUE3.jpg";
import TECNOCAMON20SERENITYBLUE4 from "assets/tecno/TECNOCAMON20/TECNOCAMON20SERENITYBLUE/TECNOCAMON20SERENITYBLUE4.jpg";
import TECNOCAMON20SERENITYBLUE5 from "assets/tecno/TECNOCAMON20/TECNOCAMON20SERENITYBLUE/TECNOCAMON20SERENITYBLUE5.jpg";

import TECNOCAMON20PRODARKWELKIN1 from "assets/tecno/TECNOCAMON20PRO/TECNOCAMON20PRODARKWELKIN/TECNOCAMON20PRODARKWELKIN1.jpg";
import TECNOCAMON20PRODARKWELKIN2 from "assets/tecno/TECNOCAMON20PRO/TECNOCAMON20PRODARKWELKIN/TECNOCAMON20PRODARKWELKIN2.jpg";
import TECNOCAMON20PRODARKWELKIN3 from "assets/tecno/TECNOCAMON20PRO/TECNOCAMON20PRODARKWELKIN/TECNOCAMON20PRODARKWELKIN3.jpg";
import TECNOCAMON20PRODARKWELKIN4 from "assets/tecno/TECNOCAMON20PRO/TECNOCAMON20PRODARKWELKIN/TECNOCAMON20PRODARKWELKIN4.jpg";
import TECNOCAMON20PROSERENITYBLUE1 from "assets/tecno/TECNOCAMON20PRO/TECNOCAMON20PROSERENITYBLUE/TECNOCAMON20PROSERENITYBLUE1.jpg";
import TECNOCAMON20PROSERENITYBLUE2 from "assets/tecno/TECNOCAMON20PRO/TECNOCAMON20PROSERENITYBLUE/TECNOCAMON20PROSERENITYBLUE2.jpg";
import TECNOCAMON20PROSERENITYBLUE3 from "assets/tecno/TECNOCAMON20PRO/TECNOCAMON20PROSERENITYBLUE/TECNOCAMON20PROSERENITYBLUE3.jpg";
import TECNOCAMON20PROSERENITYBLUE4 from "assets/tecno/TECNOCAMON20PRO/TECNOCAMON20PROSERENITYBLUE/TECNOCAMON20PROSERENITYBLUE4.jpg";
import TECNOCAMON20PROSERENITYBLUE5 from "assets/tecno/TECNOCAMON20PRO/TECNOCAMON20PROSERENITYBLUE/TECNOCAMON20PROSERENITYBLUE5.jpg";

import TECNOCAMON30BASALTICDARK1 from "assets/tecno/TECNOCAMON30/TECNOCAMON30BASALTICDARK/TECNOCAMON30BASALTICDARK1.jpg";
import TECNOCAMON30BASALTICDARK2 from "assets/tecno/TECNOCAMON30/TECNOCAMON30BASALTICDARK/TECNOCAMON30BASALTICDARK2.jpg";
import TECNOCAMON30BASALTICDARK3 from "assets/tecno/TECNOCAMON30/TECNOCAMON30BASALTICDARK/TECNOCAMON30BASALTICDARK3.jpg";
import TECNOCAMON30BASALTICDARK4 from "assets/tecno/TECNOCAMON30/TECNOCAMON30BASALTICDARK/TECNOCAMON30BASALTICDARK4.jpg";
import TECNOCAMON30BASALTICDARK5 from "assets/tecno/TECNOCAMON30/TECNOCAMON30BASALTICDARK/TECNOCAMON30BASALTICDARK5.jpg";
import TECNOCAMON30UYUNISALTWHITE1 from "assets/tecno/TECNOCAMON30/TECNOCAMON30UYUNISALTWHITE/TECNOCAMON30UYUNISALTWHITE1.jpg";
import TECNOCAMON30UYUNISALTWHITE2 from "assets/tecno/TECNOCAMON30/TECNOCAMON30UYUNISALTWHITE/TECNOCAMON30UYUNISALTWHITE2.jpg";
import TECNOCAMON30UYUNISALTWHITE3 from "assets/tecno/TECNOCAMON30/TECNOCAMON30UYUNISALTWHITE/TECNOCAMON30UYUNISALTWHITE3.jpg";
import TECNOCAMON30UYUNISALTWHITE4 from "assets/tecno/TECNOCAMON30/TECNOCAMON30UYUNISALTWHITE/TECNOCAMON30UYUNISALTWHITE4.jpg";
import TECNOCAMON30UYUNISALTWHITE5 from "assets/tecno/TECNOCAMON30/TECNOCAMON30UYUNISALTWHITE/TECNOCAMON30UYUNISALTWHITE5.jpg";

import TECNOCAMON30PREMIERLAVABLACK1 from "assets/tecno/TECNOCAMON30PREMIER/TECNOCAMON30PREMIERLAVABLACK/TECNOCAMON30PREMIERLAVABLACK1.jpg";
import TECNOCAMON30PREMIERLAVABLACK2 from "assets/tecno/TECNOCAMON30PREMIER/TECNOCAMON30PREMIERLAVABLACK/TECNOCAMON30PREMIERLAVABLACK2.jpg";
import TECNOCAMON30PREMIERLAVABLACK3 from "assets/tecno/TECNOCAMON30PREMIER/TECNOCAMON30PREMIERLAVABLACK/TECNOCAMON30PREMIERLAVABLACK3.jpg";
import TECNOCAMON30PREMIERLAVABLACK4 from "assets/tecno/TECNOCAMON30PREMIER/TECNOCAMON30PREMIERLAVABLACK/TECNOCAMON30PREMIERLAVABLACK4.jpg";
import TECNOCAMON30PREMIERLAVABLACK5 from "assets/tecno/TECNOCAMON30PREMIER/TECNOCAMON30PREMIERLAVABLACK/TECNOCAMON30PREMIERLAVABLACK5.jpg";
import TECNOCAMON30PREMIERSNOWYSILVER1 from "assets/tecno/TECNOCAMON30PREMIER/TECNOCAMON30PREMIERSNOWYSILVER/TECNOCAMON30PREMIERSNOWYSILVER1.jpg";
import TECNOCAMON30PREMIERSNOWYSILVER2 from "assets/tecno/TECNOCAMON30PREMIER/TECNOCAMON30PREMIERSNOWYSILVER/TECNOCAMON30PREMIERSNOWYSILVER2.jpg";
import TECNOCAMON30PREMIERSNOWYSILVER3 from "assets/tecno/TECNOCAMON30PREMIER/TECNOCAMON30PREMIERSNOWYSILVER/TECNOCAMON30PREMIERSNOWYSILVER3.jpg";
import TECNOCAMON30PREMIERSNOWYSILVER4 from "assets/tecno/TECNOCAMON30PREMIER/TECNOCAMON30PREMIERSNOWYSILVER/TECNOCAMON30PREMIERSNOWYSILVER4.jpg";
import TECNOCAMON30PREMIERSNOWYSILVER5 from "assets/tecno/TECNOCAMON30PREMIER/TECNOCAMON30PREMIERSNOWYSILVER/TECNOCAMON30PREMIERSNOWYSILVER5.jpg";

import TECNOPHANTOMX2MOONLIGHTSILVER1 from "assets/tecno/TECNOPHANTOMX2/TECNOPHANTOMX2MOONLIGHTSILVER/TECNOPHANTOMX2MOONLIGHTSILVER1.jpg";
import TECNOPHANTOMX2MOONLIGHTSILVER2 from "assets/tecno/TECNOPHANTOMX2/TECNOPHANTOMX2MOONLIGHTSILVER/TECNOPHANTOMX2MOONLIGHTSILVER2.jpg";
import TECNOPHANTOMX2MOONLIGHTSILVER3 from "assets/tecno/TECNOPHANTOMX2/TECNOPHANTOMX2MOONLIGHTSILVER/TECNOPHANTOMX2MOONLIGHTSILVER3.jpg";
import TECNOPHANTOMX2MOONLIGHTSILVER4 from "assets/tecno/TECNOPHANTOMX2/TECNOPHANTOMX2MOONLIGHTSILVER/TECNOPHANTOMX2MOONLIGHTSILVER4.jpg";
import TECNOPHANTOMX2MOONLIGHTSILVER5 from "assets/tecno/TECNOPHANTOMX2/TECNOPHANTOMX2MOONLIGHTSILVER/TECNOPHANTOMX2MOONLIGHTSILVER5.jpg";
import TECNOPHANTOMX2STARDUSTGREY1 from "assets/tecno/TECNOPHANTOMX2/TECNOPHANTOMX2STARDUSTGREY/TECNOPHANTOMX2STARDUSTGREY1.jpg";
import TECNOPHANTOMX2STARDUSTGREY2 from "assets/tecno/TECNOPHANTOMX2/TECNOPHANTOMX2STARDUSTGREY/TECNOPHANTOMX2STARDUSTGREY2.jpg";
import TECNOPHANTOMX2STARDUSTGREY3 from "assets/tecno/TECNOPHANTOMX2/TECNOPHANTOMX2STARDUSTGREY/TECNOPHANTOMX2STARDUSTGREY3.jpg";

import TECNOPHANTOMX2PROMARSORANGE1 from "assets/tecno/TECNOPHANTOMX2PRO/TECNOPHANTOMX2PROMARSORANGE/TECNOPHANTOMX2PROMARSORANGE1.jpg";
import TECNOPHANTOMX2PROMARSORANGE2 from "assets/tecno/TECNOPHANTOMX2PRO/TECNOPHANTOMX2PROMARSORANGE/TECNOPHANTOMX2PROMARSORANGE2.jpg";
import TECNOPHANTOMX2PROMARSORANGE3 from "assets/tecno/TECNOPHANTOMX2PRO/TECNOPHANTOMX2PROMARSORANGE/TECNOPHANTOMX2PROMARSORANGE3.jpg";
import TECNOPHANTOMX2PROMARSORANGE4 from "assets/tecno/TECNOPHANTOMX2PRO/TECNOPHANTOMX2PROMARSORANGE/TECNOPHANTOMX2PROMARSORANGE4.jpg";
import TECNOPHANTOMX2PROMARSORANGE5 from "assets/tecno/TECNOPHANTOMX2PRO/TECNOPHANTOMX2PROMARSORANGE/TECNOPHANTOMX2PROMARSORANGE5.jpg";
import TECNOPHANTOMX2PROSTARDUSTGREY1 from "assets/tecno/TECNOPHANTOMX2PRO/TECNOPHANTOMX2PROSTARDUSTGREY/TECNOPHANTOMX2PROSTARDUSTGREY1.jpg";
import TECNOPHANTOMX2PROSTARDUSTGREY2 from "assets/tecno/TECNOPHANTOMX2PRO/TECNOPHANTOMX2PROSTARDUSTGREY/TECNOPHANTOMX2PROSTARDUSTGREY2.jpg";
import TECNOPHANTOMX2PROSTARDUSTGREY3 from "assets/tecno/TECNOPHANTOMX2PRO/TECNOPHANTOMX2PROSTARDUSTGREY/TECNOPHANTOMX2PROSTARDUSTGREY3.jpg";
import TECNOPHANTOMX2PROSTARDUSTGREY4 from "assets/tecno/TECNOPHANTOMX2PRO/TECNOPHANTOMX2PROSTARDUSTGREY/TECNOPHANTOMX2PROSTARDUSTGREY4.jpg";

import TECNOPOVA6NEOAURORACLOUD1 from "assets/tecno/TECNOPOVA6NEO/TECNOPOVA6NEOAURORACLOUD/TECNOPOVA6NEOAURORACLOUD1.jpeg";
import TECNOPOVA6NEOAURORACLOUD2 from "assets/tecno/TECNOPOVA6NEO/TECNOPOVA6NEOAURORACLOUD/TECNOPOVA6NEOAURORACLOUD2.jpeg";
import TECNOPOVA6NEOAURORACLOUD3 from "assets/tecno/TECNOPOVA6NEO/TECNOPOVA6NEOAURORACLOUD/TECNOPOVA6NEOAURORACLOUD3.jpeg";
import TECNOPOVA6NEOAURORACLOUD4 from "assets/tecno/TECNOPOVA6NEO/TECNOPOVA6NEOAURORACLOUD/TECNOPOVA6NEOAURORACLOUD4.jpeg";
import TECNOPOVA6NEOAZURESKY1 from "assets/tecno/TECNOPOVA6NEO/TECNOPOVA6NEOAZURESKY/TECNOPOVA6NEOAZURESKY1.jpeg";
import TECNOPOVA6NEOAZURESKY2 from "assets/tecno/TECNOPOVA6NEO/TECNOPOVA6NEOAZURESKY/TECNOPOVA6NEOAZURESKY2.jpeg";
import TECNOPOVA6NEOAZURESKY3 from "assets/tecno/TECNOPOVA6NEO/TECNOPOVA6NEOAZURESKY/TECNOPOVA6NEOAZURESKY3.jpeg";
import TECNOPOVA6NEOAZURESKY4 from "assets/tecno/TECNOPOVA6NEO/TECNOPOVA6NEOAZURESKY/TECNOPOVA6NEOAZURESKY4.jpeg";
import TECNOPOVA6NEOMIDNIGHTSHADOW1 from "assets/tecno/TECNOPOVA6NEO/TECNOPOVA6NEOMIDNIGHTSHADOW/TECNOPOVA6NEOMIDNIGHTSHADOW1.jpeg";
import TECNOPOVA6NEOMIDNIGHTSHADOW2 from "assets/tecno/TECNOPOVA6NEO/TECNOPOVA6NEOMIDNIGHTSHADOW/TECNOPOVA6NEOMIDNIGHTSHADOW2.jpeg";
import TECNOPOVA6NEOMIDNIGHTSHADOW3 from "assets/tecno/TECNOPOVA6NEO/TECNOPOVA6NEOMIDNIGHTSHADOW/TECNOPOVA6NEOMIDNIGHTSHADOW3.jpeg";
import TECNOPOVA6NEOMIDNIGHTSHADOW4 from "assets/tecno/TECNOPOVA6NEO/TECNOPOVA6NEOMIDNIGHTSHADOW/TECNOPOVA6NEOMIDNIGHTSHADOW4.jpeg";
import TECNOPOVA6NEOMIDNIGHTSHADOW5 from "assets/tecno/TECNOPOVA6NEO/TECNOPOVA6NEOMIDNIGHTSHADOW/TECNOPOVA6NEOMIDNIGHTSHADOW5.jpeg";
import TECNOPOVA6NEOMIDNIGHTSHADOW6 from "assets/tecno/TECNOPOVA6NEO/TECNOPOVA6NEOMIDNIGHTSHADOW/TECNOPOVA6NEOMIDNIGHTSHADOW6.jpeg";

import TECNOPOVA6PROCOMETGREEN1 from "assets/tecno/TECNOPOVA6PRO/TECNOPOVA6PROCOMETGREEN/TECNOPOVA6PROCOMETGREEN1.jpeg";
import TECNOPOVA6PROCOMETGREEN2 from "assets/tecno/TECNOPOVA6PRO/TECNOPOVA6PROCOMETGREEN/TECNOPOVA6PROCOMETGREEN2.jpeg";
import TECNOPOVA6PROCOMETGREEN3 from "assets/tecno/TECNOPOVA6PRO/TECNOPOVA6PROCOMETGREEN/TECNOPOVA6PROCOMETGREEN3.jpeg";
import TECNOPOVA6PROCOMETGREEN4 from "assets/tecno/TECNOPOVA6PRO/TECNOPOVA6PROCOMETGREEN/TECNOPOVA6PROCOMETGREEN4.jpeg";
import TECNOPOVA6PROCOMETGREEN5 from "assets/tecno/TECNOPOVA6PRO/TECNOPOVA6PROCOMETGREEN/TECNOPOVA6PROCOMETGREEN5.jpeg";
import TECNOPOVA6PROMETEORITEGREY1 from "assets/tecno/TECNOPOVA6PRO/TECNOPOVA6PROMETEORITEGREY/TECNOPOVA6PROMETEORITEGREY1.jpg";
import TECNOPOVA6PROMETEORITEGREY2 from "assets/tecno/TECNOPOVA6PRO/TECNOPOVA6PROMETEORITEGREY/TECNOPOVA6PROMETEORITEGREY2.jpg";
import TECNOPOVA6PROMETEORITEGREY3 from "assets/tecno/TECNOPOVA6PRO/TECNOPOVA6PROMETEORITEGREY/TECNOPOVA6PROMETEORITEGREY3.jpg";
import TECNOPOVA6PROMETEORITEGREY4 from "assets/tecno/TECNOPOVA6PRO/TECNOPOVA6PROMETEORITEGREY/TECNOPOVA6PROMETEORITEGREY4.jpg";
import TECNOPOVA6PROMETEORITEGREY5 from "assets/tecno/TECNOPOVA6PRO/TECNOPOVA6PROMETEORITEGREY/TECNOPOVA6PROMETEORITEGREY5.jpg";

import TECNOSPARK30CAURORCLOUD1 from "assets/tecno/TECNOSPARK30C/TECNOSPARK30CAURORCLOUD/TECNOSPARK30CAURORCLOUD1.jpeg";
import TECNOSPARK30CAURORCLOUD2 from "assets/tecno/TECNOSPARK30C/TECNOSPARK30CAURORCLOUD/TECNOSPARK30CAURORCLOUD2.jpeg";
import TECNOSPARK30CAURORCLOUD3 from "assets/tecno/TECNOSPARK30C/TECNOSPARK30CAURORCLOUD/TECNOSPARK30CAURORCLOUD3.jpeg";
import TECNOSPARK30CAURORCLOUD4 from "assets/tecno/TECNOSPARK30C/TECNOSPARK30CAURORCLOUD/TECNOSPARK30CAURORCLOUD4.jpeg";
import TECNOSPARK30CAURORCLOUD5 from "assets/tecno/TECNOSPARK30C/TECNOSPARK30CAURORCLOUD/TECNOSPARK30CAURORCLOUD5.jpeg";
import TECNOSPARK30CMIDNIGHTSHADOW1 from "assets/tecno/TECNOSPARK30C/TECNOSPARK30CMIDNIGHTSHADOW/TECNOSPARK30CMIDNIGHTSHADOW1.jpeg";
import TECNOSPARK30CMIDNIGHTSHADOW2 from "assets/tecno/TECNOSPARK30C/TECNOSPARK30CMIDNIGHTSHADOW/TECNOSPARK30CMIDNIGHTSHADOW2.jpeg";
import TECNOSPARK30CMIDNIGHTSHADOW3 from "assets/tecno/TECNOSPARK30C/TECNOSPARK30CMIDNIGHTSHADOW/TECNOSPARK30CMIDNIGHTSHADOW3.jpeg";
import TECNOSPARK30CMIDNIGHTSHADOW4 from "assets/tecno/TECNOSPARK30C/TECNOSPARK30CMIDNIGHTSHADOW/TECNOSPARK30CMIDNIGHTSHADOW4.jpeg";
import TECNOSPARK30CMIDNIGHTSHADOW5 from "assets/tecno/TECNOSPARK30C/TECNOSPARK30CMIDNIGHTSHADOW/TECNOSPARK30CMIDNIGHTSHADOW5.jpeg";
import TECNOSPARK30CMIDNIGHTSHADOW6 from "assets/tecno/TECNOSPARK30C/TECNOSPARK30CMIDNIGHTSHADOW/TECNOSPARK30CMIDNIGHTSHADOW6.jpeg";

export const TECNOPHONES = [
  {
    id: "TECNO1",
    name: "TECNO CAMON 20",
    brand: "TECNO",
    salesPrice: 10499,
    specialOffer: true,
    trendingPhone: true,
    rating: 5,
    newArrival: true,
    mrp: 13999,
    colors: [
      {
        id: 1,
        name: "ART EDITION",
        images: [
          TECNOCAMON20ARTEDITION1,
          TECNOCAMON20ARTEDITION2,
          TECNOCAMON20ARTEDITION3,
          TECNOCAMON20ARTEDITION4,
          TECNOCAMON20ARTEDITION5,
        ],
      },
      {
        id: 2,
        name: "Serenity Blue",
        images: [
          TECNOCAMON20SERENITYBLUE1,
          TECNOCAMON20SERENITYBLUE2,
          TECNOCAMON20SERENITYBLUE3,
          TECNOCAMON20SERENITYBLUE4,
          TECNOCAMON20SERENITYBLUE5,
        ],
      },
    ],
    specifications: {
      Processor: "MediaTek Helio G85 Octa core ",
      Display: "6.67″ (16.94 cm) 60Hz AMOLED ",
      "Rear Camera": "64+2+0.08 MP",
      "Front Camera": "32 MP",
      "RAM | Storage": "8 GB | 256 GB ",
      Battery: "5000 mAh | 33W Fast Charging ",
      Network: "Dual SIM: 4G & 4G",
      OS: "Android v13 ",
    },
  },

  {
    id: "TECNO2",
    name: "TECNO CAMON 20 PRO",
    brand: "TECNO",
    salesPrice: 17999,
    specialOffer: true,
    trendingPhone: true,
    rating: 5,
    newArrival: true,
    mrp: 24999,
    colors: [
      {
        id: 1,
        name: "Dark Welkin",
        images: [
          TECNOCAMON20PRODARKWELKIN1,
          TECNOCAMON20PRODARKWELKIN2,
          TECNOCAMON20PRODARKWELKIN3,
          TECNOCAMON20PRODARKWELKIN4,
        ],
      },
      {
        id: 2,
        name: "Serenity Blue",
        images: [
          TECNOCAMON20PROSERENITYBLUE1,
          TECNOCAMON20PROSERENITYBLUE2,
          TECNOCAMON20PROSERENITYBLUE3,
          TECNOCAMON20PROSERENITYBLUE4,
          TECNOCAMON20PROSERENITYBLUE5,
        ],
      },
    ],
    specifications: {
      Processor: "MediaTek Dimensity 8050 Octa core ",
      Display: "6.67″ (16.94 cm) 120Hz AMOLED ",
      "Rear Camera": "64+2+2 MP",
      "Front Camera": "32 MP",
      "RAM | Storage": "8 GB | 128 GB ",
      Battery: "5000 mAh | 33W Fast Charging ",
      Network: "Dual SIM: 5G & 4G",
      OS: "Android v13",
    },
  },

  {
    id: "TECNO3",
    name: "TECNO CAMON 30",
    brand: "TECNO",
    salesPrice: 22999,
    specialOffer: true,
    trendingPhone: true,
    rating: 5,
    newArrival: true,
    mrp: 27999,
    colors: [
      {
        id: 1,
        name: "Basaltic Dark",
        images: [
          TECNOCAMON30BASALTICDARK1,
          TECNOCAMON30BASALTICDARK2,
          TECNOCAMON30BASALTICDARK3,
          TECNOCAMON30BASALTICDARK4,
          TECNOCAMON30BASALTICDARK5,
        ],
      },
      {
        id: 2,
        name: "Uyunisalt White",
        images: [
          TECNOCAMON30UYUNISALTWHITE1,
          TECNOCAMON30UYUNISALTWHITE2,
          TECNOCAMON30UYUNISALTWHITE3,
          TECNOCAMON30UYUNISALTWHITE4,
          TECNOCAMON30UYUNISALTWHITE5,
        ],
      },
    ],
    specifications: {
      Processor: "MediaTek Dimensity 7020 Octa core ",
      Display: "6.78″ (17.22 cm) 120Hz LTPS AMOLED ",
      "Rear Camera": "50+2 MP",
      "Front Camera": "50 MP",
      "RAM | Storage": "8 GB | 256 GB ",
      Battery: "5000 mAh | 33W Fast Charging ",
      Network: "Dual SIM: 5G & 5G",
      OS: "Android v14 ",
    },
  },

  {
    id: "TECNO4",
    name: "TECNO CAMON 30 PREMIER",
    brand: "TECNO",
    salesPrice: 39999,
    specialOffer: true,
    trendingPhone: true,
    rating: 5,
    newArrival: true,
    mrp: 47999,
    colors: [
      {
        id: 1,
        name: "Lava Black",
        images: [
          TECNOCAMON30PREMIERLAVABLACK1,
          TECNOCAMON30PREMIERLAVABLACK2,
          TECNOCAMON30PREMIERLAVABLACK3,
          TECNOCAMON30PREMIERLAVABLACK4,
          TECNOCAMON30PREMIERLAVABLACK5,
        ],
      },
      {
        id: 2,
        name: "Snow Silver",
        images: [
          TECNOCAMON30PREMIERSNOWYSILVER1,
          TECNOCAMON30PREMIERSNOWYSILVER2,
          TECNOCAMON30PREMIERSNOWYSILVER3,
          TECNOCAMON30PREMIERSNOWYSILVER4,
          TECNOCAMON30PREMIERSNOWYSILVER5,
        ],
      },
    ],
    specifications: {
      Processor: "MediaTek Dimensity 8200 Octa core ",
      Display: "6.77″ (17.2 cm) 120Hz LTPO AMOLED ",
      "Rear Camera": "50+50+50 MP",
      "Front Camera": "50 MP",
      "RAM | Storage": "12 GB | 512 GB ",
      Battery: "5000 mAh | 70W Fast Charging ",
      Network: "Dual SIM: 5G & 5G",
      OS: "Android v14",
    },
  },

  {
    id: "TECNO5",
    name: "TECNO PHANTOM X2",
    brand: "TECNO",
    salesPrice: 36999,
    specialOffer: true,
    trendingPhone: true,
    rating: 5,
    newArrival: true,
    mrp: 51999,
    colors: [
      {
        id: 1,
        name: "Moonlight Silver",
        images: [
          TECNOPHANTOMX2MOONLIGHTSILVER1,
          TECNOPHANTOMX2MOONLIGHTSILVER2,
          TECNOPHANTOMX2MOONLIGHTSILVER3,
          TECNOPHANTOMX2MOONLIGHTSILVER4,
          TECNOPHANTOMX2MOONLIGHTSILVER5,
        ],
      },
      {
        id: 2,
        name: "Stardust Grey",
        images: [
          TECNOPHANTOMX2STARDUSTGREY1,
          TECNOPHANTOMX2STARDUSTGREY2,
          TECNOPHANTOMX2STARDUSTGREY3,
        ],
      },
    ],
    specifications: {
      Processor: "MediaTek Dimensity 9000 Octa core ",
      Display: "6.8″ (17.27 cm) 120Hz AMOLED ",
      "Rear Camera": "64+13+2 MP",
      "Front Camera": "32 MP",
      "RAM | Storage": "8 GB | 256 GB ",
      Battery: "5160 mAh | 45W Fast Charging ",
      Network: "Dual SIM: 5G & 4G",
      OS: "Android v12 ",
    },
  },

  {
    id: "TECNO6",
    name: "TECNO PHANTOM X2 PRO",
    brand: "TECNO",
    salesPrice: 44999,
    specialOffer: true,
    trendingPhone: true,
    rating: 5,
    newArrival: true,
    mrp: 61999,
    colors: [
      {
        id: 1,
        name: "Mars Orange",
        images: [
          TECNOPHANTOMX2PROMARSORANGE1,
          TECNOPHANTOMX2PROMARSORANGE2,
          TECNOPHANTOMX2PROMARSORANGE3,
          TECNOPHANTOMX2PROMARSORANGE4,
          TECNOPHANTOMX2PROMARSORANGE5,
        ],
      },
      {
        id: 2,
        name: "Stardust Grey",
        images: [
          TECNOPHANTOMX2PROSTARDUSTGREY1,
          TECNOPHANTOMX2PROSTARDUSTGREY2,
          TECNOPHANTOMX2PROSTARDUSTGREY3,
          TECNOPHANTOMX2PROSTARDUSTGREY4,
        ],
      },
    ],
    specifications: {
      Processor: "MediaTek Dimensity 9000 Octa core ",
      Display: "6.8″ (17.27 cm) 120Hz AMOLED ",
      "Rear Camera": "50+50+13 MP",
      "Front Camera": "32 MP",
      "RAM | Storage": "12 GB | 256 GB ",
      Battery: "5160 mAh | 45W Fast Charging ",
      Network: "Dual SIM: 5G & 4G",
      OS: "Android v12 ",
    },
  },

  {
    id: "TECNO5",
    name: "TECNO POVA 6 NEO",
    brand: "TECNO",
    salesPrice: 12999,
    specialOffer: true,
    trendingPhone: true,
    rating: 5,
    newArrival: true,
    mrp: 15999,
    colors: [
      {
        id: 1,
        name: "Aurora Cloud",
        images: [
          TECNOPOVA6NEOAURORACLOUD1,
          TECNOPOVA6NEOAURORACLOUD2,
          TECNOPOVA6NEOAURORACLOUD3,
          TECNOPOVA6NEOAURORACLOUD4,
        ],
      },
      {
        id: 2,
        name: "Azur Sky",
        images: [
          TECNOPOVA6NEOAZURESKY1,
          TECNOPOVA6NEOAZURESKY2,
          TECNOPOVA6NEOAZURESKY3,
          TECNOPOVA6NEOAZURESKY4,
        ],
      },
      {
        id: 3,
        name: "Midnight Shadow",
        images: [
          TECNOPOVA6NEOMIDNIGHTSHADOW1,
          TECNOPOVA6NEOMIDNIGHTSHADOW2,
          TECNOPOVA6NEOMIDNIGHTSHADOW3,
          TECNOPOVA6NEOMIDNIGHTSHADOW4,
          TECNOPOVA6NEOMIDNIGHTSHADOW5,
          TECNOPOVA6NEOMIDNIGHTSHADOW6,
        ],
      },
    ],
    specifications: {
      Processor: "MediaTek Dimensity 6300 Octa core ",
      Display: "6.67″ (16.94 cm) 120Hz IPS LCD ",
      "Rear Camera": "108 MP",
      "Front Camera": "8 MP",
      "RAM | Storage": "6 GB | 128 GB ",
      Battery: "5000 mAh | 18W Fast Charging ",
      Network: "Dual SIM: 5G & 5G",
      OS: "Android v14 ",
    },
  },

  {
    id: "TECNO6",
    name: "TECNO POVA 6 PRO",
    brand: "TECNO",
    salesPrice: 21999,
    specialOffer: true,
    trendingPhone: true,
    rating: 5,
    newArrival: true,
    mrp: 24999,
    colors: [
      {
        id: 1,
        name: "Comet Green",
        images: [
          TECNOPOVA6PROCOMETGREEN1,
          TECNOPOVA6PROCOMETGREEN2,
          TECNOPOVA6PROCOMETGREEN3,
          TECNOPOVA6PROCOMETGREEN4,
          TECNOPOVA6PROCOMETGREEN5,
        ],
      },
      {
        id: 2,
        name: "Meteorite Grey",
        images: [
          TECNOPOVA6PROMETEORITEGREY1,
          TECNOPOVA6PROMETEORITEGREY2,
          TECNOPOVA6PROMETEORITEGREY3,
          TECNOPOVA6PROMETEORITEGREY4,
          TECNOPOVA6PROMETEORITEGREY5,
        ],
      },
    ],
    specifications: {
      Processor: "MediaTek Dimensity 6080 Octa core ",
      Display: "6.78″ (17.22 cm) 120Hz AMOLED ",
      "Rear Camera": "108+2+0.08 MP",
      "Front Camera": "32 MP",
      "RAM | Storage": "12 GB | 256 GB ",
      Battery: "6000 mAh | 70W Fast Charging ",
      Network: "Dual SIM: 5G & 5G",
      OS: "Android v14 ",
    },
  },

  {
    id: "TECNO7",
    name: "TECNO SPARK 30 C",
    brand: "TECNO",
    salesPrice: 10499,
    specialOffer: true,
    trendingPhone: true,
    rating: 5,
    newArrival: true,
    mrp: 24999,
    colors: [
      {
        id: 1,
        name: "Auror Cloud",
        images: [
          TECNOSPARK30CAURORCLOUD1,
          TECNOSPARK30CAURORCLOUD2,
          TECNOSPARK30CAURORCLOUD3,
          TECNOSPARK30CAURORCLOUD4,
          TECNOSPARK30CAURORCLOUD5,
        ],
      },
      {
        id: 2,
        name: "Midnight Shadow",
        images: [
          TECNOSPARK30CMIDNIGHTSHADOW1,
          TECNOSPARK30CMIDNIGHTSHADOW2,
          TECNOSPARK30CMIDNIGHTSHADOW3,
          TECNOSPARK30CMIDNIGHTSHADOW4,
          TECNOSPARK30CMIDNIGHTSHADOW5,
          TECNOSPARK30CMIDNIGHTSHADOW6,
        ],
      },
    ],
    specifications: {
      Processor: "MediaTek Dimensity 6300 Octa core ",
      Display: "6.67″ (16.94 cm) 120Hz IPS LCD ",
      "Rear Camera": "48 MP",
      "Front Camera": "8 MP",
      "RAM | Storage": "4 GB | 128 GB ",
      Battery: "5000 mAh | 18W Fast Charging ",
      Network: "Dual SIM: 5G & 5G",
      OS: "Android v14",
    },
  },
];
