import REDMI135GBLACKDIAMOND1 from "assets/mi/REDMI135G/REDMI135GBLACKDIAMOND/REDMI135GBLACKDIAMOND1.jpg";
import REDMI135GBLACKDIAMOND2 from "assets/mi/REDMI135G/REDMI135GBLACKDIAMOND/REDMI135GBLACKDIAMOND2.jpg";
import REDMI135GBLACKDIAMOND3 from "assets/mi/REDMI135G/REDMI135GBLACKDIAMOND/REDMI135GBLACKDIAMOND3.jpg";
import REDMI135GBLACKDIAMOND4 from "assets/mi/REDMI135G/REDMI135GBLACKDIAMOND/REDMI135GBLACKDIAMOND4.jpg";
import REDMI135GBLACKDIAMOND5 from "assets/mi/REDMI135G/REDMI135GBLACKDIAMOND/REDMI135GBLACKDIAMOND5.jpg";

import REDMI135GHAWAIIANBLUE1 from "assets/mi/REDMI135G/REDMI135GHAWAIIANBLUE/REDMI135GHAWAIIANBLUE1.jpg";
import REDMI135GHAWAIIANBLUE2 from "assets/mi/REDMI135G/REDMI135GHAWAIIANBLUE/REDMI135GHAWAIIANBLUE2.jpg";
import REDMI135GHAWAIIANBLUE3 from "assets/mi/REDMI135G/REDMI135GHAWAIIANBLUE/REDMI135GHAWAIIANBLUE3.jpg";
import REDMI135GHAWAIIANBLUE4 from "assets/mi/REDMI135G/REDMI135GHAWAIIANBLUE/REDMI135GHAWAIIANBLUE4.jpg";
import REDMI135GHAWAIIANBLUE5 from "assets/mi/REDMI135G/REDMI135GHAWAIIANBLUE/REDMI135GHAWAIIANBLUE5.jpg";

import REDMI135GORCHIDPINK1 from "assets/mi/REDMI135G/REDMI135GORCHIDPINK/REDMI135GORCHIDPINK1.jpg";
import REDMI135GORCHIDPINK2 from "assets/mi/REDMI135G/REDMI135GORCHIDPINK/REDMI135GORCHIDPINK2.jpg";
import REDMI135GORCHIDPINK3 from "assets/mi/REDMI135G/REDMI135GORCHIDPINK/REDMI135GORCHIDPINK3.jpg";
import REDMI135GORCHIDPINK4 from "assets/mi/REDMI135G/REDMI135GORCHIDPINK/REDMI135GORCHIDPINK4.jpg";
import REDMI135GORCHIDPINK5 from "assets/mi/REDMI135G/REDMI135GORCHIDPINK/REDMI135GORCHIDPINK5.jpg";

import REDMINOTE13PROPLUS5GFUSIONBLACK1 from "assets/mi/REDMINOTE13PROPLUS5G/REDMINOTE13PROPLUS5GFUSIONBLACK/REDMINOTE13PROPLUS5GFUSIONBLACK1.jpg";
import REDMINOTE13PROPLUS5GFUSIONBLACK2 from "assets/mi/REDMINOTE13PROPLUS5G/REDMINOTE13PROPLUS5GFUSIONBLACK/REDMINOTE13PROPLUS5GFUSIONBLACK2.jpg";
import REDMINOTE13PROPLUS5GFUSIONBLACK3 from "assets/mi/REDMINOTE13PROPLUS5G/REDMINOTE13PROPLUS5GFUSIONBLACK/REDMINOTE13PROPLUS5GFUSIONBLACK3.jpg";
import REDMINOTE13PROPLUS5GFUSIONBLACK4 from "assets/mi/REDMINOTE13PROPLUS5G/REDMINOTE13PROPLUS5GFUSIONBLACK/REDMINOTE13PROPLUS5GFUSIONBLACK4.jpg";
import REDMINOTE13PROPLUS5GFUSIONBLACK5 from "assets/mi/REDMINOTE13PROPLUS5G/REDMINOTE13PROPLUS5GFUSIONBLACK/REDMINOTE13PROPLUS5GFUSIONBLACK5.jpg";

import REDMINOTE13PROPLUS5GFUSIONPURPLE1 from "assets/mi/REDMINOTE13PROPLUS5G/REDMINOTE13PROPLUS5GFUSIONPURPLE/REDMINOTE13PROPLUS5GFUSIONPURPLE1.jpg";
import REDMINOTE13PROPLUS5GFUSIONPURPLE2 from "assets/mi/REDMINOTE13PROPLUS5G/REDMINOTE13PROPLUS5GFUSIONPURPLE/REDMINOTE13PROPLUS5GFUSIONPURPLE2.jpg";
import REDMINOTE13PROPLUS5GFUSIONPURPLE3 from "assets/mi/REDMINOTE13PROPLUS5G/REDMINOTE13PROPLUS5GFUSIONPURPLE/REDMINOTE13PROPLUS5GFUSIONPURPLE3.jpg";
import REDMINOTE13PROPLUS5GFUSIONPURPLE4 from "assets/mi/REDMINOTE13PROPLUS5G/REDMINOTE13PROPLUS5GFUSIONPURPLE/REDMINOTE13PROPLUS5GFUSIONPURPLE4.jpg";
import REDMINOTE13PROPLUS5GFUSIONPURPLE5 from "assets/mi/REDMINOTE13PROPLUS5G/REDMINOTE13PROPLUS5GFUSIONPURPLE/REDMINOTE13PROPLUS5GFUSIONPURPLE5.jpg";

import REDMINOTE13PROPLUS5GFUSIONWHITE1 from "assets/mi/REDMINOTE13PROPLUS5G/REDMINOTE13PROPLUS5GFUSIONWHITE/REDMINOTE13PROPLUS5GFUSIONWHITE1.jpg";
import REDMINOTE13PROPLUS5GFUSIONWHITE2 from "assets/mi/REDMINOTE13PROPLUS5G/REDMINOTE13PROPLUS5GFUSIONWHITE/REDMINOTE13PROPLUS5GFUSIONWHITE2.jpg";
import REDMINOTE13PROPLUS5GFUSIONWHITE3 from "assets/mi/REDMINOTE13PROPLUS5G/REDMINOTE13PROPLUS5GFUSIONWHITE/REDMINOTE13PROPLUS5GFUSIONWHITE3.jpg";
import REDMINOTE13PROPLUS5GFUSIONWHITE4 from "assets/mi/REDMINOTE13PROPLUS5G/REDMINOTE13PROPLUS5GFUSIONWHITE/REDMINOTE13PROPLUS5GFUSIONWHITE4.jpg";
import REDMINOTE13PROPLUS5GFUSIONWHITE5 from "assets/mi/REDMINOTE13PROPLUS5G/REDMINOTE13PROPLUS5GFUSIONWHITE/REDMINOTE13PROPLUS5GFUSIONWHITE5.jpg";

const phone = [
  {
    id: "MI5",
    name: "MI 13 5G 6/128",
    brand: "MI",
    image: REDMI135GBLACKDIAMOND1,
    launchDate: "03-06-2024",
    salesPrice: 12999,
    specialOffer: true,
    trendingPhone: true,
    rating: 5,
    newArrival: true,
    mrp: 17999,
    specifications: {
      Processor: "Snapdragon 4 Gen 2 Octa core ",
      Display: "6.79″ (17.25 cm) 120Hz IPS LCD ",
      "Rear Camera": "108+2 MP",
      "Front Camera": "13 MP",
      "RAM | Storage": "6 GB | 128 GB ",
      Battery: "5030 mAh | 33W Fast Charging ",
      Network: "Dual SIM: 5G & 5G",
      OS: "Android v14 ",
    },
    colors: [
      {
        id: 1,
        name: "black diamond",
        images: [
          REDMI135GBLACKDIAMOND1,
          REDMI135GBLACKDIAMOND2,
          REDMI135GBLACKDIAMOND3,
          REDMI135GBLACKDIAMOND4,
          REDMI135GBLACKDIAMOND5,
        ],
      },

      {
        id: 2,
        name: "HAWAIIAN BLUE",
        images: [
          REDMI135GHAWAIIANBLUE1,
          REDMI135GHAWAIIANBLUE2,
          REDMI135GHAWAIIANBLUE3,
          REDMI135GHAWAIIANBLUE4,
          REDMI135GHAWAIIANBLUE5,
        ],
      },

      {
        id: 3,
        name: "ORCHIDPINK1",
        images: [
          REDMI135GORCHIDPINK1,
          REDMI135GORCHIDPINK2,
          REDMI135GORCHIDPINK3,
          REDMI135GORCHIDPINK4,
          REDMI135GORCHIDPINK5,
        ],
      },
    ],
  },
  {
    id: "MI5",
    name: "MI 13 5G 8/128",
    brand: "MI",
    image: REDMI135GBLACKDIAMOND1,
    launchDate: "03-06-2024",
    salesPrice: 14499,
    specialOffer: true,
    trendingPhone: true,
    rating: 5,
    newArrival: true,
    mrp: 19999,
    specifications: {
      Processor: "Snapdragon 4 Gen 2 Octa core ",
      Display: "6.79″ (17.25 cm) 120Hz IPS LCD ",
      "Rear Camera": "108+2 MP",
      "Front Camera": "13 MP",
      "RAM | Storage": "6 GB | 128 GB ",
      Battery: "5030 mAh | 33W Fast Charging ",
      Network: "Dual SIM: 5G & 5G",
      OS: "Android v14 ",
    },
    colors: [
      {
        id: 1,
        name: "black diamond",
        images: [
          REDMI135GBLACKDIAMOND1,
          REDMI135GBLACKDIAMOND2,
          REDMI135GBLACKDIAMOND3,
          REDMI135GBLACKDIAMOND4,
          REDMI135GBLACKDIAMOND5,
        ],
      },

      {
        id: 2,
        name: "HAWAIIAN BLUE",
        images: [
          REDMI135GHAWAIIANBLUE1,
          REDMI135GHAWAIIANBLUE2,
          REDMI135GHAWAIIANBLUE3,
          REDMI135GHAWAIIANBLUE4,
          REDMI135GHAWAIIANBLUE5,
        ],
      },

      {
        id: 3,
        name: "ORCHIDPINK1",
        images: [
          REDMI135GORCHIDPINK1,
          REDMI135GORCHIDPINK2,
          REDMI135GORCHIDPINK3,
          REDMI135GORCHIDPINK4,
          REDMI135GORCHIDPINK5,
        ],
      },
    ],
  },

  {
    id: "MI5",
    name: "MI Note 13 Pro Plus 5G 8/256",
    brand: "MI",
    image: REDMINOTE13PROPLUS5GFUSIONBLACK1,
    launchDate: "21-09-2023",
    salesPrice: 27999,
    specialOffer: true,
    trendingPhone: true,
    rating: 5,
    newArrival: true,
    mrp: 33999,
    specifications: {
      Processor: "MediaTek Dimensity 7200 Ultra Octa core ",
      Display: "6.67″ (16.94 cm) 120Hz AMOLED ",
      "Rear Camera": "200+8+2 MP",
      "Front Camera": "16 MP",
      "RAM | Storage": "8 GB | 256 GB ",
      Battery: "5000 mAh | 120W Fast Charging ",
      Network: "Dual SIM: 5G & 5G",
      OS: "Android v13 ",
    },
    colors: [
      {
        id: 1,
        name: "Fusion Black",
        images: [
          REDMINOTE13PROPLUS5GFUSIONBLACK1,
          REDMINOTE13PROPLUS5GFUSIONBLACK2,
          REDMINOTE13PROPLUS5GFUSIONBLACK3,
          REDMINOTE13PROPLUS5GFUSIONBLACK4,
          REDMINOTE13PROPLUS5GFUSIONBLACK5,
        ],
      },

      {
        id: 2,
        name: "Fusion Purple",
        images: [
          REDMINOTE13PROPLUS5GFUSIONPURPLE1,
          REDMINOTE13PROPLUS5GFUSIONPURPLE2,
          REDMINOTE13PROPLUS5GFUSIONPURPLE3,
          REDMINOTE13PROPLUS5GFUSIONPURPLE4,
          REDMINOTE13PROPLUS5GFUSIONPURPLE5,
        ],
      },

      {
        id: 3,
        name: "Fusion White",
        images: [
          REDMINOTE13PROPLUS5GFUSIONWHITE1,
          REDMINOTE13PROPLUS5GFUSIONWHITE2,
          REDMINOTE13PROPLUS5GFUSIONWHITE3,
          REDMINOTE13PROPLUS5GFUSIONWHITE4,
          REDMINOTE13PROPLUS5GFUSIONWHITE5,
        ],
      },
    ],
  },
];
