export const initialValues = {
  productName: "",
  brand: "",
  ram: "",
  storage: "",
  price: "",
  mrp: "",
  series: "",
  networkType: "",
  category: "1",
  display: "",
  frontCamera: "",
  rearCamera: "",
  variants: [],
  os: "",
  processor: "",
  battery: "",
};
